### ISSUE TITLE
Welcome Back! What about Edge and Spotify patches?

### ISSUE THREAD

**Issue by darkalexis1990** [Blaukovitch/GOOGLE_CHROME_Windows_7#1]
hi , welcome back @Blaukovitch 

so great  news you are back!

would you transfer also into the MDL forums?

also what patching **x86** Edge https://learn.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel

and spotify **x86** https://www.spotify.com/us/download/other/

looking forward for news from you!

take care :)

**Comment by Blaukovitch** [comment]
@darkalexis1990, hi!
I glad to see you in this repo ^)


"also what patching x86 Edge https://learn.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel
and spotify x86 https://www.spotify.com/us/download/other/"
Sorry! At this time at lot of work.

I think for now I'll just keep an eye on the current repository for closure, as Google and Microsoft are now actively monitoring it after the release of the **paid version** of the Google Chrome browser.

**Comment by darkalexis1990** [comment]
@Blaukovitch  :(

**Comment by darkalexis1990** [comment]
@Blaukovitch  please come to mdl forum . i need edge and spotify :( ..... looking forward to have good news from you...

**Comment by darkalexis1990** [comment]
@Blaukovitch its too unfair chrome only patched and not spotify and edge :(

**Comment by i486** [comment]
Hey, @darkalexis1990,

Just wanted to drop a quick note about your recent comment. I get where you're coming from with the frustration about the lack of patching for Spotify and Edge, but let's cut Blaukovitch some slack. 

He already mentioned that he's got a lot on his plate, and there's a real risk of his repo getting blocked again. Instead of guilt-tripping him, let's be patient and show some appreciation for what he's already done. Remember, he doesn't owe us anything.

Cheers,
i486

**Comment by Blaukovitch** [comment]
> spotify :(

https://github.com/Blaukovitch/GOOGLE_CHROME_Windows_7/releases/tag/spotify_new
Please, test with Open TAB (login).

**Comment by adeii** [comment]
The latest Spotify x64 could install and run with VxKex 1.1.1.
Check Enable, Report (as Win 10), Use stronger report.

https://download.scdn.co/SpotifyFullSetupX64.exe - full download.
https://download.scdn.co/SpotifyFullSetup.exe - full x86 download. Installed but still can not run with VxKex.

**Comment by darkalexis1990** [comment]
> Hey, @darkalexis1990,
> 
> Just wanted to drop a quick note about your recent comment. I get where you're coming from with the frustration about the lack of patching for Spotify and Edge, but let's cut Blaukovitch some slack.
> 
> He already mentioned that he's got a lot on his plate, and there's a real risk of his repo getting blocked again. Instead of guilt-tripping him, let's be patient and show some appreciation for what he's already done. Remember, he doesn't owe us anything.
> 
> Cheers, i486

im not guilt-tripping NOONE. im THANKING @Blaukovitch every day for his work. I JUST TOLD HIM  TO GO ON MDL FORUMS so no one can watching him every time and make sure that his work wont be deleted. so @i486 youre completely  wrong.bye

**Comment by veso266** [comment]
wow, you managed to get back :smile: not sure what you had to do to get ur repo back but, its amazing its back

Thank you for you good work

**Comment by Blaukovitch** [comment]
I’ll be back ^)

Thanks for you support!

> Chrome Enterprise Premium 

https://cloud.google.com/blog/products/identity-security/introducing-chrome-enterprise-premium

I need the Trial version of THIS paid browser.

**Comment by darkalexis1990** [comment]
> The latest Spotify x86/x64 could install and run with VxKex 1.1.1. Few api-ms-X.dll are needed. Check Enable, Report (as Win 10), Use stronger report. Spotify is strict about modding, emulating, bithacking. They could drop down this repo again. Use web player better.
> 
> https://download.scdn.co/SpotifyFullSetupX64.exe - full download. https://download.scdn.co/SpotifyFullSetup.exe - full x86 download.
> 
> Enable VxKex for Spotify.exe and try on Win 7 32bit (run with X.bat, login goes to default browser): https://github.com/adeii/supermium-portable/releases/download/C125/SpotiXy-portable-1.2.37.701-x86-VxKex.7z

hi can you answer me on the above-> does the vxkex 1.1.1 conflict with the bypass tool? cause the nt 6.1 is still updated we use update or win7 machines.

thanks.

**Comment by adeii** [comment]
> cause the nt 6.1 is still updated

It is tested with kernel 6.1.7601.24545. It is Win 7 SP1 + Bypass ESU v12 + UpdatePack7 from 23.12.12 (newer can not boot in my PC). No conflicts.

**Comment by greenozon** [comment]
@adeii    any hints regarding
>Bypass ESU v12 + UpdatePack7 from 23.12.12

thanks

**Comment by darkalexis1990** [comment]
@Blaukovitch after discusiion on the MDL forum someone had the idea to use the pached api dll's from the edge 125 windows 7 repo that is already patched and IT WORKED. that guy also tested 126 and also worked.the thing is that with the Edge Stable 127.0.2651.74 the patched does not work anymore, cause the API dllls needs again patching. can you please patch/update your api dlls so we can test with 127? thanks youre the best!!! looking for news from you.

https://github.com/Blaukovitch/EDGE.Patcher/issues/1

**Comment by adeii** [comment]
> any hints regarding

BypassESU - Somewhere in this thread https://forums.mydigitallife.net/threads/bypass-windows-7-extended-security-updates-eligibility.80606/

After testing, the current Win7 can install BypassESU v12 to continue to install subsequent ESU patches, but you have to go to the Microsoft Update Catalog website to download the patches yourself.
Updates could be found here: https://hackandpwn.com/windows-7-esu-patching/
or use the newest UpdatePack7R2; https://blog.simplix.info/updatepack7r2/

Also useful:
https://github.com/abbodi1406/dotNetFx4xW7A
https://github.com/abbodi1406/vcredist

**Comment by greenozon** [comment]
Thanks a lot!
that was very helpful for sure

**Comment by darkalexis1990** [comment]
> The latest Spotify x86/x64 could install and run with VxKex 1.1.1. Few api-ms-X.dll are needed. Check Enable, Report (as Win 10), Use stronger report. Spotify is strict about modding, emulating, bithacking. They could drop down this repo again. Use web player better.
> 
> https://download.scdn.co/SpotifyFullSetupX64.exe - full download. https://download.scdn.co/SpotifyFullSetup.exe - full x86 download.
> 
> Enable VxKex for Spotify.exe and try on Win 7 32bit (run with X.bat, login goes to default browser): https://github.com/adeii/supermium-portable/releases/download/C125/SpotiXy-portable-1.2.37.701-x86-VxKex.7z

@adeii can you tried to run discord with vxkex???

**Comment by darkalexis1990** [comment]
> The latest Spotify x86/x64 could install and run with VxKex 1.1.1. Few api-ms-X.dll are needed. Check Enable, Report (as Win 10), Use stronger report. Spotify is strict about modding, emulating, bithacking. They could drop down this repo again. Use web player better.
> 
> https://download.scdn.co/SpotifyFullSetupX64.exe - full download. https://download.scdn.co/SpotifyFullSetup.exe - full x86 download.
> 
> Enable VxKex for Spotify.exe and try on Win 7 32bit (run with X.bat, login goes to default browser): https://github.com/adeii/supermium-portable/releases/download/C125/SpotiXy-portable-1.2.37.701-x86-VxKex.7z

Spotify Neither Discord Works Anymore with VxKex.
