### ISSUE TITLE
Should we put the GOOGLE_CHROME_Windows_7 folder in the protected "program files" folder or can we put it in any location, for example C: or D: ?

### ISSUE THREAD

**Issue by trimechee** [Blaukovitch/GOOGLE_CHROME_Windows_7#20]
Hi Mr @Blaukovitch , I would like to know please what is the best choice to avoid possible problems, should we put the GOOGLE_CHROME_Windows_7 folder in the famous protected system folder "program files" or can we put it in any location, for example C: ? or D: ?

**Comment by Blaukovitch** [comment]
Hi!
>  should we put the GOOGLE_CHROME_Windows_7 folder in the famous protected system folder "program files" or can we put it in any location, for example C: ? or D: ?

You unpack in any folder and any disk. Optional - in protected folders. No difference.

**Comment by trimechee** [comment]
Great ! Thanks :) 💯
