### ISSUE TITLE
ElectronMail 5.2.3

### ISSUE THREAD

**Issue by ask2018** [Blaukovitch/GOOGLE_CHROME_Windows_7#7]
@Blaukovitch could you try to fix latest ElectronMail 5.2.3 based on Electron 32.0.1?
Not even latest available VxKex version helps here unfortunately.
https://github.com/vladimiry/ElectronMail/releases/tag/v5.2.3

**Comment by Blaukovitch** [comment]
Okay, i see whats.

**Comment by Blaukovitch** [comment]
Resolved here:
https://github.com/Blaukovitch/GOOGLE_CHROME_Windows_7/releases/tag/ElectronMail_523

**Comment by ask2018** [comment]
Thank you. Very nice work :) I'm just testing it and seems to be running fine. I'll report back if I'll find any issues. I'm closing the issue for now and will reopen if needed.

**Comment by ask2018** [comment]
After few hours of testing it seems to be working fine. I just found one issue, but that seems to be some incompatibility with other software starting at same time and its easy to fix. 

Here is the problem description just for info.ElectronMail is auto starting after system boot with some other applications on my system. After reboot I've been getting some COM error msg from Sandboxie - https://github.com/sandboxie-plus/Sandboxie/ (also auto starts) and ElectronMail didn't start properly. There was no icon in tray and I needed to kill the ElectronMail process manually. But I have not ElectronMail sandboxed. It is running without the sandbox. So I changed the order of the startup and added ElectronMail as last with 3 seconds waiting time and now it works properly.

**Comment by ask2018** [comment]
@Blaukovitch I have another update after 2 weeks of usage. It is working fine 99.9% of time, but two times I've got some odd crashes on sandboxed programs I'm using. I've been unable to do screenshots, as I needed to kill the Electronmail process first to be able to run anything and I'm unable to reproduce it. If this will appear once more, I'll try to do photo of the monitor. But looks like there is some incompatibility/bug with the Sandboxie software and rarely it can also occur outside of startup time. Maybe if you can test what I'm describing in the post above, it might give you some hint.

**Comment by Blaukovitch** [comment]
@ask2018, Did it display any errors? You can try to run in logging mode (there is a special bat file `!!DEBUG_LOG.bat`).
`ElectronMail.exe --enable-logging --v=7`

**Comment by ask2018** [comment]
@Blaukovitch There was no error from ElectronMail side. But there was an error from the Sandboxie and also from the software running inside Sandboxie - that software fully crashed and the error there was something about breakpoint reached - maybe same or similar error as described here: https://github.com/Blaukovitch/GOOGLE_CHROME_Windows_7/issues/3
I’m unable to reproduce this error, so I need to wait on next case. Last time when this happened I didn’t have time to play with that, because I needed to do some other work on the PC and the system was somehow fully partially stuck. For example I was unable to run any software included Task Manager. But I was able to kill the ElectronMail process in the tray using System Hacker software running on my system. After I killed the ElectronMail process Task Manager started. I’ll try to use the debug  bat file and also make a screenshot of the error if this will happen next time and report here.

**Comment by ask2018** [comment]
@Blaukovitch I've got another crash here and now I've been able to make screenshot. I think the error is not exactly the same as before, but looks like there is some memory leak. The system is basically unusable before I kill the ElectronMail process, so I've been unable to check the memory usage, but when I was trying to run another software, it was complaining about memory. In such case the leak must be huge, because my system got 64GB of RAM.  And I'm reminding, that ElectronMail is not running inside the Sandboxie process.

Here is the screenshot of what I've been able to get with PrtScr on my keyboard.

![electronmail_crash](https://github.com/user-attachments/assets/ee992b8a-0a72-4fdf-b6ce-fab057db5ca8)

**Comment by ask2018** [comment]
@Blaukovitch I see you released version 5.3.0. Are those crashes above fixed there?

**Comment by Blaukovitch** [comment]
> see you released version 5.3.0. Are those crashes above fixed there?

@ask2018, Yeah, I was fixing one of the crashes. But it's not a sure thing that this is the one. Try the new version and tell me how it behaves.

**Comment by ask2018** [comment]
@Blaukovitch Ok thanks a lot. I'll test it, but it might take a while. This memory leak causing crashes is little bit problematic, as it is affecting stability of the system and other applications and I need to test only when potential crash will not cause me any issue with other software and data lost. That means I cannot let it running all the time.
