### ISSUE TITLE
Asking for help

### ISSUE THREAD

**Issue by adeii** [Blaukovitch/GOOGLE_CHROME_Windows_7#9]
Dear @Blaukovitch ,
What am I missing in this to make it work without VxKex? I have no useful skills with x96Debug.
(vivaldi.exe and vivaldi.dll has few breakpoints.)
https://github.com/adeii/supermium-portable/releases/tag/v6.9

**Comment by Blaukovitch** [comment]
>  it work without VxKex? 

Hello! 
But you have problems, if vivaldi start WITH VxKex?

**Comment by Blaukovitch** [comment]
> Yes, when using another PC with Win 8.

What is kind of problem? Browser not start or any errors shows?

**Comment by adeii** [comment]
Remain in background, as running process but no windows nor frame at all. Not even an error pop-up.
